### ISSUE TITLE
Does not note only for 2017

### ISSUE THREAD

**Issue by shmuelie** [madskristensen/TypeScriptDefinitionGenerator#2]
The README.md should note that this is for 2017 only, as most aren't there yet (at least for work).

**Comment by tjrobinson** [comment]
@madskristensen Does this mean that the TypeScript Definition Generator is not needed for VS2015 users as Web Essentials already covers the functionality? If so, I'm struggling to find the "Generate TypeScript Definition" menu item.

**Comment by madskristensen** [comment]
@tjrobinson Correct. Here's how to access it when right-clicking a .cs file:

![image](https://cloud.githubusercontent.com/assets/1258877/22113782/511940ea-de1c-11e6-8acd-69fd2805b645.png)

**Comment by tjrobinson** [comment]
@madskristensen Ah, thanks! Easy now I know how :)

**Comment by Mrsevic** [comment]
For the teams who are transitioning from the legacy Microsoft technologies such as a Silverlight it is extremely important to have the tool that will do the job in both ides. Will work on forking a vs 2015 only version.  Mostly because of the shortcoming that the old version has when generating certain types.
